INSERT INTO restaurants (name,address,typeOfFood,rate,price) VALUES ('Hong Kong Tea House','565 W 200 S, Salt Lake City, UT 84101','Dim Sum',4.4,'$$');
INSERT INTO restaurants (name,address,typeOfFood,rate,price) VALUES ('Sasa Kitchen','2095 E 1300 S','Chinese small plates',4.1,'$');
INSERT INTO restaurants (name,address,typeOfFood,rate,price) VALUES ('Tea Bar','1201 Wilmington Ave #109','Chinese small plates',4.3,'$');
INSERT INTO restaurants (name,address,typeOfFood,rate,price) VALUES ("Tosh's Ramen",'1465 State St','Japanese',4.6,'$');
INSERT INTO restaurants (name,address,typeOfFood,rate,price) VALUES ('Red House','1465 State St #10','Chinese',4,'$$');
INSERT INTO restaurants (name,address,typeOfFood,rate,price) VALUES ('Aroma','715 E 12300 S','Indian',4,'$$');
INSERT INTO restaurants (name,address,typeOfFood,rate,price) VALUES ('King Buffet','The Family Center at Taylorsville, 5668 S Redwood Rd, Taylorsville, UT 84123','Chinese',4,'$');
INSERT INTO restaurants (name,address,typeOfFood,rate,price) VALUES ('Tucanos Brazilian Grill','162 400 W, Salt Lake City, UT 84101','Brazilian',4,'$$');
INSERT INTO restaurants (name,address,typeOfFood,rate,price) VALUES ('Pho 33','7640 State St, Midvale, UT 84047','Vietnamese',4.2,'$');
INSERT INTO restaurants (name,address,typeOfFood,rate,price) VALUES ('Red Corner','46 W 7200 S, Midvale, UT 84047','Chinese',4.2,'$$');
INSERT INTO restaurants (name,address,typeOfFood,rate,price) VALUES ('Jang Soo Jang','58 E 3750 S, South Salt Lake, UT 84115','Korean',4.4,'$$');
INSERT INTO restaurants (name,address,typeOfFood,rate,price) VALUES ('Lucky 13','135 W 1300 S SLC, UT 84115','American',4.8,'$$');
INSERT INTO restaurants (name,address,typeOfFood,rate,price) VALUES ('Moochies','232 E 800 S SLC, UT 84111','Sandwhiches',4.5,'$');
INSERT INTO restaurants (name,address,typeOfFood,rate,price) VALUES ('Pats BBQ','155 W Commonwealth Ave SLC, UT 84115','BBQ',4.5,'$$');
INSERT INTO restaurants (name,address,typeOfFood,rate,price) VALUES ('R&R BBQ','307 W 600 S SLC, UT 84101','BBQ',4.3,'$$');
INSERT INTO restaurants (name,address,typeOfFood,rate,price) VALUES ('Penny Anns','1810 Main St, Salt Lake City, UT 84115','American',4.1,'$$');
INSERT INTO restaurants (name,address,typeOfFood,rate,price) VALUES ('Blue Plate Diner','2041 S 2100 E SLC 84108','Breakfast',4.6,'$');
INSERT INTO restaurants (name,address,typeOfFood,rate,price) VALUES ('Rusted Sun Pizzeria','2010 State Street SLC UT 84115','Pizza',4.6,'$$');
INSERT INTO restaurants (name,address,typeOfFood,rate,price) VALUES ('Red Iguana','736 W North Temple SLC UT 84116','Mexican',4.5,'$$');
INSERT INTO restaurants (name,address,typeOfFood,rate,price) VALUES ('La Cai Noodle House','961 S State St SLC UT 84111','Vietnamese',4.8,'$$');
